### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by regisin** [alpacahq/alpaca-trade-api-python#137]
Simply seting up and trying out the examples provided (LongShort and Martingale) fail.

_LongShort:_
Exception in thread Thread-182:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "5813.py", line 275, in getTotalPrice
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/alpaca_trade_api/rest.py", line 262, in get_barset
    resp = self.data_get('/bars/{}'.format(timeframe), params)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/alpaca_trade_api/rest.py", line 147, in data_get
    return self._request('GET', path, data, base_url=base_url)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/alpaca_trade_api/rest.py", line 100, in _request
    return self._one_request(method, url, opts, retry)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/alpaca_trade_api/rest.py", line 121, in _one_request
    resp.raise_for_status()
  File "/Users/regisin/Library/Python/3.6/lib/python/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://data.alpaca.markets/v2/bars/minute?symbols=**ANY 1st SYMBOL FROM LIST**&limit=1

_Martingale_:
Traceback (most recent call last):
  File "Martin.py", line 190, in <module>
    trader = MartingaleTrader()
  File "Martin.py", line 57, in __init__
    self.api.cancel_all_orders()
AttributeError: 'REST' object has no attribute 'cancel_all_orders'

Are the examples tested after updates?

**Comment by ttt733** [comment]
It looks to me, for the Martingale file error, you're on an earlier version of the library that didn't have the cancel_all_orders endpoint. What version of the SDK do you have? (Your file's line numbers also don't match what's in the repo, so I can't debug too well without knowing what changes you've made.)

For the long/short example, I'm not sure what could cause it to reach the v2 data endpoint unless you've made some changes to the library code - data_get, which is being called, looks like this:
```
def data_get(self, path, data=None):
        base_url = get_data_url()
        return self._request(
            'GET', path, data, base_url=base_url, api_version='v1'
        )
```
`api_version` should always be v1, not v2.

Please reopen with some more information if the issue persists after updating your version of the SDK to the latest one available on pypi.
