### ISSUE TITLE
Websocket streaming does not work with paper trading creds

### ISSUE THREAD

**Issue by qlikstar** [alpacahq/alpaca-trade-api-python#175]
This script is failing since yesterday with the following error:

```
#!/usr/bin/env python

import alpaca_trade_api as tradeapi
from alpaca_trade_api.stream2 import StreamConn
from pprint import pprint

base_url = 'https://paper-api.alpaca.markets'
api_key_id = 'PKTKMECJGYAJ87YN9V07'
api_secret = 'myfakeapisecret'

conn = StreamConn(base_url=base_url, key_id=api_key_id, secret_key=api_secret)
api = tradeapi.REST(
    base_url=base_url,
    key_id=api_key_id,
    secret_key=api_secret
)
account = api.get_account()
pprint(account)

@conn.on(r'.*')
async def on_data(conn, channel, data):
    print(channel)
    pprint(data)

# A.SPY will work, because it only goes to Polygon
# conn.run(['A.SPY'])

# account_updates fail, being sent to websocket stream
conn.run(['account_updates', 'trade_updates', 'A.SPY'])
```
Error that I see is : 
```
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "/Users/smishra/PycharmProjects/AlgoT/test.py", line 29, in <module>
    conn.run(['account_updates', 'trade_updates', 'A.SPY'])
  File "/Users/smishra/anaconda3/lib/python3.7/site-packages/alpaca_trade_api/stream2.py", line 159, in run
    loop.run_until_complete(self.subscribe(initial_channels))
  File "/Users/smishra/anaconda3/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/Users/smishra/anaconda3/lib/python3.7/site-packages/alpaca_trade_api/stream2.py", line 128, in subscribe
    await self._ensure_polygon()
  File "/Users/smishra/anaconda3/lib/python3.7/site-packages/alpaca_trade_api/stream2.py", line 85, in _ensure_polygon
    await self.polygon.connect()
  File "/Users/smishra/anaconda3/lib/python3.7/site-packages/alpaca_trade_api/polygon/streamconn.py", line 44, in connect
    if await self.authenticate():
  File "/Users/smishra/anaconda3/lib/python3.7/site-packages/alpaca_trade_api/polygon/streamconn.py", line 70, in authenticate
    raise ValueError('Invalid Polygon credentials, '
ValueError: Invalid Polygon credentials, Failed to authenticate: {'ev': 'status', 'status': 'auth_failed', 'message': 'authentication failed'}
```

Has there been a change since yesterday or am I doing something wrong?

**Comment by kfmfe04** [comment]
This has been happening since FRI afternoon, Mar 27 (worked fine for many weeks previously).  It started working again on Mon, Mar 28, morning 4:30PST and failed again at 12:37PST.

I suspect there are server-end issues, but we need a confirmation from alpaca.

**Comment by umitanuki** [comment]
Sorry for the trouble, there was some change around polygon integration. This will be fixed later today.
