### ISSUE TITLE
TypeError: 'int' object is not subscriptable when streaming data from polygon

### ISSUE THREAD

**Issue by nhabbott** [alpacahq/alpaca-trade-api-python#195]
I'm currently modifying the moment-trading-example repo and whenever it attempts to buy a stock, I get the following error. I'm pretty positive that the error is occurring when analyzing bars. Occasionally, it will buy one or two stocks then die with the same error. [My code can be found here](https://pastebin.com/bwDJa3X9), just so you all can use the line numbers in the error (if it happens to be my code).

```
Watching 167 symbols.
Task exception was never retrieved
future: <Task finished name='Task-9' coro=<StreamConn._consume_msg() done, defined at C:\Python38\lib\site-packages\alpaca_trade_api\polygon\streamconn.py:99> exception=TypeError("'int' object is not subscriptable")>
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\alpaca_trade_api\polygon\streamconn.py", line 103, in _consume_msg
    await self._dispatch(data)
  File "C:\Python38\lib\site-packages\alpaca_trade_api\polygon\streamconn.py", line 240, in _dispatch
    await handler(self, channel, ent)
  File "momentum.py", line 251, in handle_second_bar
    if (daily_pct_change > .04 and data.close > high_15m and volume_today[symbol] > 30000):
TypeError: 'int' object is not subscriptable
```

**Comment by t-shah** [comment]
Link does not work

**Comment by nhabbott** [comment]
> 
> 
> Link does not work

I have updated the link.

**Comment by drew887** [comment]
Hey closing this one out due to inactivity and also we removed polygon
