### ISSUE TITLE
Using datetime objects doesn't work

### ISSUE THREAD

**Issue by VanushVaswani** [alpacahq/alpaca-trade-api-python#228]
```
import datetime                                                                 
from datetime import timedelta                                                  
import alpaca_trade_api as tradeapi                                             
                                                                                
api = tradeapi.REST()                                                           
                                                                                
now = datetime.datetime.now()                                                   
                                                                                
begin = now - datetime.timedelta(days=7)                                        
                                                                                
aapl = api.polygon.historic_agg_v2('AAPL', 1, 'minute',  _from=begin, to=now).df
```

Gets

```
Traceback (most recent call last):
  File "api.py", line 11, in <module>
    aapl = api.polygon.historic_agg_v2('AAPL', 1, 'minute',  _from=begin, to=now).df
  File "/vanfiles/anaconda3/lib/python3.7/site-packages/alpaca_trade_api/polygon/rest.py", line 148, in historic_agg_v2
    _from).date().isoformat(),
  File "/vanfiles/anaconda3/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/vanfiles/anaconda3/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 646, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "/vanfiles/anaconda3/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 725, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "/vanfiles/anaconda3/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 207, in split
    return list(cls(s))
  File "/vanfiles/anaconda3/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 76, in __init__
    '{itype}'.format(itype=instream.__class__.__name__))
TypeError: Parser must be a string or character stream, not datetime
```

```
>>> alpaca_trade_api.__version__
'0.48'
```

**Comment by shlomikushchi** [comment]
Hi, this issue is fixed in the master branch. 
not yet released.
please install it in the meantime like this:
`pip install -U git+https://github.com/alpacahq/alpaca-trade-api-python`
