### ISSUE TITLE
I updated from 0.46 to 0.48 and I cant stream.

### ISSUE THREAD

**Issue by dans-acc** [alpacahq/alpaca-trade-api-python#267]
Hello,

I recently updated from 0.46 to 0.48 and in doing so, I no longer am able to stream market data. Please find the error below:

```python
Traceback (most recent call last):
  File "/home/me/Workbench/Bot/bot/feed.py", line 383, in <module>
    feed.run()
  File "/home/me/Workbench/Bot/bot/feed.py", line 336, in run
    self._apca_conn.run(channels)
  File "/home/me/miniconda3/envs/bot-env/lib/python3.7/site-packages/alpaca_trade_api/stream2.py", line 275, in run
    loop.run_until_complete(self.subscribe(initial_channels))
  File "/home/me/miniconda3/envs/bot-env/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/home/me/miniconda3/envs/bot-env/lib/python3.7/site-packages/alpaca_trade_api/stream2.py", line 243, in subscribe
    'the right data_stream)').format(c))
ValueError: unknown channel A.AAPL (you may need to specify the right data_stream)
```

**Comment by shlomikushchi** [comment]
Hi,
I'm assuming you're using the polygon data stream? (if you're trying to get data for A.AAPL you probably do)
on version 0.48 we introduced the new default data stream - the Alpaca data stream
in order to still get the polygon data stream you need to specify it explicitly as described in the readme file in this repo:
 https://github.com/alpacahq/alpaca-trade-api-python

![image](https://user-images.githubusercontent.com/7924802/87552514-75c0ae80-c6ba-11ea-9810-94cc21fbda29.png)

**Comment by dans-acc** [comment]
If the API making a transition away from Polygon? If so, will it support second bars?
