### ISSUE TITLE
Error is placing a limit buy order

### ISSUE THREAD

**Issue by purugupta99** [alpacahq/alpaca-trade-api-python#275]
```json
apiObj.submit_order(
    symbol='GE',
    side='buy',
    type='limit',
    qty='3000',
    time_in_force='day',
    order_class='bracket',
    take_profit=dict(
        limit_price=price,
    ),
    stop_loss=dict(
        stop_price=price * 0.995,
        limit_price=price * 0.995
    ) 
)
```
I am trying to place a limit order with some price but getting error: limit orders require a limit price

```
Traceback (most recent call last):
  File "trade.py", line 125, in <module>
    make_order(api, symbol, bidprice)
  File "trade.py", line 29, in make_order
    limit_price=bidprice * 0.995
  File "/home/shell_basher/anaconda3/lib/python3.7/site-packages/alpaca_trade_api/rest.py", line 304, in submit_order
    resp = self.post('/orders', params)
  File "/home/shell_basher/anaconda3/lib/python3.7/site-packages/alpaca_trade_api/rest.py", line 161, in post
    return self._request('POST', path, data)
  File "/home/shell_basher/anaconda3/lib/python3.7/site-packages/alpaca_trade_api/rest.py", line 121, in _request
    return self._one_request(method, url, opts, retry)
  File "/home/shell_basher/anaconda3/lib/python3.7/site-packages/alpaca_trade_api/rest.py", line 150, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: limit orders require a limit price
```

**Comment by shlomikushchi** [comment]
Hi
it looks like you submitted a bracket order (not a limit order) with a limit condition but without the limit price
a bracket order is (in this case) 3 orders combined to 1
you buy a position, then you have 2 orders to protect you from fast movements (stop order and take profit order)
in other words, the limit_price you entered is for the second order, not the first.

if you only want a simple limit order, don't use the bracket type
and in any case, you need to add the limit_price right here:
![image](https://user-images.githubusercontent.com/7924802/88369445-bbefcf00-cd98-11ea-89c0-7c0fc4f4e7cd.png)

**Comment by purugupta99** [comment]
Got it, thank you!
