### ISSUE TITLE
API install 

### ISSUE THREAD

**Issue by glstott** [alpacahq/alpaca-trade-api-python#32]
I am having troubles installing the alpaca trade api. Currently I'm getting an error when I try to install either via pipenv or pip. Let me know what other printouts would help in troubleshooting. 
OS: Ubuntu 18.04

**Full error: **
The directory '/home/garrick/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/garrick/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting alpaca-trade-api
  Downloading https://files.pythonhosted.org/packages/45/a5/7ceb9477f9d87c50ef47b4b1a504b37c4ec1ff5c0f72a449eb786e127887/alpaca-trade-api-0.19.tar.gz
Collecting asyncio-nats-client (from alpaca-trade-api)
  Downloading https://files.pythonhosted.org/packages/f6/a0/3e9a55cfe262699a2ce98714e14a7381bc674112f567af80457d16ea9b2f/asyncio-nats-client-0.8.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-dsdJrG/asyncio-nats-client/setup.py", line 2, in <module>
        from nats.aio.client import __version__
      File "nats/__init__.py", line 22
        yield from nc.connect(**options)
                 ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-dsdJrG/asyncio-nats-client/

**Comment by glstott** [comment]
It installed fine using pip3. We can close the issue if this is expected.
