### ISSUE TITLE
"Max retries exceeded with url" exception when trying to use API.get_account() and API.list_positions()

### ISSUE THREAD

**Issue by PerrySong** [alpacahq/alpaca-trade-api-python#340]
Hi I just opened a paper account and used the api_key_id/Secret Key found on this page: https://app.alpaca.markets/paper/dashboard/overview to test out the API.
 But I got below exception even after I regenerate my apiKey.
 
 My code:
 ```py
import alpaca_trade_api as trade_api
API = trade_api.REST(key_id='mykey', secret_key='my_secret_key', base_url='https://paper-api.alpaca.markets')
account = API.get_account()
API.list_positions()
```
Exception:
```
 File "/mypath//lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/mypath//lib/python3.7/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/mypath//lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mypath//lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/mypath//lib/python3.7/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/mypath//lib/python3.7/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/mypath//lib/python3.7/site-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/mypath//lib/python3.7/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7ffcd4a95a50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mypath//lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/mypath//lib/python3.7/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/mypath//lib/python3.7/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='paper-api.alpaca.markets', port=443): Max retries exceeded with url: /v2/account (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ffcd4a95a50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pengfeisong/Desktop/project/NoNameTradingMachine/alpacaStandBox/alpacaTest.py", line 17, in <module>
    account = API.get_account()
  File "/mypath//lib/python3.7/site-packages/alpaca_trade_api/rest.py", line 178, in get_account
    resp = self.get('/account')
  File "/mypath//lib/python3.7/site-packages/alpaca_trade_api/rest.py", line 156, in get
    return self._request('GET', path, data)
  File "/mypath//lib/python3.7/site-packages/alpaca_trade_api/rest.py", line 119, in _request
    return self._one_request(method, url, opts, retry)
  File "/mypath//lib/python3.7/site-packages/alpaca_trade_api/rest.py", line 138, in _one_request
    resp = self._session.request(method, url, **opts)
  File "/mypath//lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/mypath//lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/mypath//lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='paper-api.alpaca.markets', port=443): Max retries exceeded with url: /v2/account (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ffcd4a95a50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
```

**Comment by tjquinn1** [comment]
try it without named arguments for key_id and secret_key, that should work.

**Comment by shlomikushchi** [comment]
Hi, 
re-checked the code now locally and it works as expected. what version of the alpaca-trade-api do you have installed?

I ran this code:

```py
import alpaca_trade_api as tradeapi
api = tradeapi.REST(key_id=ALPACA_API_KEY,
                    secret_key=ALPACA_SECRET_KEY,
                    base_url='https://paper-api.alpaca.markets' )

api.get_account()
api.list_positions()

```

**Comment by PerrySong** [comment]
Hi, 
I re-checked the code just now, and it works fine this time.
ps: I was using the API right after I created my account. There might have some delay to populate my data (I guess)?

**Comment by shlomikushchi** [comment]
that could be it. yet I'm not sure what is the delay..
