### ISSUE TITLE
Websocket streaming does not work with paper trading creds

### ISSUE THREAD

**Issue by bdowling** [alpacahq/alpaca-trade-api-python#48]
For lack of a better place to post this upstream API issue, I'm posting it here.  The Alpaca websocket streaming API appears to have an issue that prevents paper trading credentials from being used to stream account_updates and trade_updates.  I would like to be able to use this to develop and test these features for production usage.  The sample program below shows how this fails, the paper credentials successfully obtain the account information, but will fail to authorize the websocket stream.

Note that this Exception below is a result of #46 PR, otherwise you would just see the authorization failure in the channel messages, which, in the provided examples, would also not be printed. e.g.

```
authenticated
Entity({'action': 'authenticate', 'status': 'unauthorized'})
authorization
Entity({'action': 'listen', 'status': 'unauthorized'})
```

```
% ./testWatch.py 
Account({   'account_blocked': False,
    'buying_power': '100000',
...
    'transfers_blocked': False})
Traceback (most recent call last):
  File "./testWatch.py", line 22, in <module>
    conn.run(['account_updates', 'trade_updates', 'A.SPY'])
  File ".../alpaca/src/alpaca-trade-api-python/alpaca_trade_api/stream2.py", line 104, in run
    loop.run_until_complete(self.subscribe(initial_channels))
  File "/home/bdowling/.pyenv/versions/3.7.1/lib/python3.7/asyncio/base_events.py", line 573, in run_until_complete
    return future.result()
  File ".../alpaca/src/alpaca-trade-api-python/alpaca_trade_api/stream2.py", line 86, in subscribe
    await self._ensure_ws()
  File ".../alpaca/src/alpaca-trade-api-python/alpaca_trade_api/stream2.py", line 71, in _ensure_ws
    self._ws = await self._connect()
  File ".../alpaca/src/alpaca-trade-api-python/alpaca_trade_api/stream2.py", line 35, in _connect
    raise ValueError("Invalid Alpaca API credentials, Failed to authenticate: {}".format(msg))
ValueError: Invalid Alpaca API credentials, Failed to authenticate: {'stream': 'authorization', 'data': {'action': 'authenticate', 'status': 'unauthorized'}}

```

```
#!/usr/bin/env python

import alpaca_trade_api as tradeapi
from userauth_paper import UserAuth
from alpaca_trade_api.stream2 import StreamConn
from pprint import pprint

conn = StreamConn(UserAuth.key, UserAuth.secret)
api = tradeapi.REST(UserAuth.key, UserAuth.secret, base_url=UserAuth.url)
account = api.get_account()
pprint(account)

@conn.on(r'.*')
async def on_data(conn, channel, data):
    print(channel)
    pprint(data)

# A.SPY will work, because it only goes to Polygon
# conn.run(['A.SPY'])

# account_updates fail, being sent to websocket stream
conn.run(['account_updates', 'trade_updates', 'A.SPY'])
```

**Comment by umitanuki** [comment]
So you are saying socket stream for account_updates and trade_updates don't succeed in authorization with paper? You are connecting to paper-api.alpaca.markets, correct?

**Comment by bdowling** [comment]
@umitanuki ahah.  So this was a user error on my part, thank you for reminding me.  You can see in the code above, I did not pass base_url into `StreamingConn()` nor use the env variable.

Closing
