### ISSUE TITLE
get_bars .df Method on Result Fails Due to Undocumented Key

### ISSUE THREAD

**Issue by jbgrunewald** [alpacahq/alpaca-trade-api-python#485]
I was running the sample where you call the get_bars API, and turn the result into a dataframe. I get the below exception locally.

```
Traceback (most recent call last):
  File "/Users/jbgrunewald/trade-bot/get_symbol.py", line 21, in <module>
    print(api.get_bars("AAPL", TimeFrame.Minute, "2021-06-08", "2021-06-08", adjustment='raw').df)
  File "/Users/jbgrunewald/trade-bot/venv/lib/python3.9/site-packages/alpaca_trade_api/entity_v2.py", line 61, in df
    df.columns = [self.mapping[c] for c in df.columns]
  File "/Users/jbgrunewald/trade-bot/venv/lib/python3.9/site-packages/alpaca_trade_api/entity_v2.py", line 61, in <listcomp>
    df.columns = [self.mapping[c] for c in df.columns]
KeyError: 'n'
```

Example Bar from the response:
```
Bar({   'c': 126.74,
    'h': 126.74,
    'l': 126.74,
    'n': 17,
    'o': 126.74,
    't': '2021-06-08T23:56:00Z',
    'v': 2199,
    'vw': 126.738663})
```

It does contain an 'n' and a 'vw' key that are not documented in the API. Any advice on what those are, and can we add support for them?

**Comment by jbgrunewald** [comment]
Looking at the docs for Polygon, which I think is what is being used behind the scenes, it seems these are documented there.

Their response keys:

```
cnumber
The close price for the symbol in the given time period.

hnumber
The highest price for the symbol in the given time period.

lnumber
The lowest price for the symbol in the given time period.

nnumber
The number of transactions in the aggregate window.

onumber
The open price for the symbol in the given time period.

tinteger
The Unix Msec timestamp for the start of the aggregate window.

vnumber
The trading volume of the symbol in the given time period.

vwnumber
The volume weighted average price.
```

**Comment by gnvk** [comment]
This should be fixed in the latest version. Please confirm and close the issue if so.
