### ISSUE TITLE
Alpaca historical data to support weekly, monthly data

### ISSUE THREAD

**Issue by akarun2405** [alpacahq/alpaca-trade-api-python#548]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

I'm trying to get historical data for other TimeFrames like weekly, monthly. When I look at the TimeFrameUnit, there's support only for Minute, Hour, Day - but not for Weekly or Monthly

Weekly may not just be querying for 5 days or Monthly can't be 30 days as some months can have more than 30 days or less than that.

Am I missing something in terms of an existing feature?

### Describe the solution you'd like.

TimeFrameUnit must include Week, Month, Year as a valid units and the data can be queried based on multiples of these new units

**Comment by akarun2405** [comment]
@gnvk sorry to poke you here. Would you know if this will be supported by alpaca?

**Comment by gnvk** [comment]
You're right, this isn't something Alpaca supports right now. The closest you can get is "5Day" and "20Day", but it isn't going to be perfect because of the market holidays.

**Comment by akarun2405** [comment]
Is this something in the development roadmap or probably not happening anytime soon?

**Comment by gnvk** [comment]
As far as I know this is not on the roadmap. My suggestion: use 1Day bars and aggregate them yourself based on your exact requirements.

**Comment by gnvk** [comment]
I have started working on this. The difficulty of this is that the start of the bar is not trivial for these timeframe units if the multiplier is bigger than 1. For 1Week or 1Month you can say that the start is the beginning of the week / month (Monday / first day of the month). For 2Week for example this is not the case. Would it be sufficient for you if we only added 1Week and 1Month?

**Comment by akarun2405** [comment]
Thank you so much! Yes, 1M, 1W and if it is easy, you could throw in 1Q (3M), 6M, 1Y as well.

Typically I never use other timeframes like 2M. But even if someone were to use, the logical way to look at it will be to coincide the starting point to be the year boundary, so (Jan, Feb), (March, April) etc etc. This way the candles will continue to make sense. 

Further more, if you look at a charting application like trading view, they support custom intervals and allow you to specify intervals like 7months (which makes no sense) but they start the first candle of the year in Jan and second candle in Aug. creating 2 unequal candles. 


My point being, for month timeframes, makes sense to coincide the start of computation with start of the year.

**Comment by akarun2405** [comment]
Excellent. Agree on all counts.

What is the approximate timeline to set my expectations on this so I can plan future development? 

Once again thank you so much! 🙏

**Comment by gnvk** [comment]
I'm done with the implementation. Hopefully it will be deployed tomorrow.

**Comment by gnvk** [comment]
``` py
> api.get_bars('AAPL', '1Week', start='2021-01-01', limit=5).df
                             open      high      low   close     volume  trade_count        vwap
timestamp                                                                                       
2021-01-04 05:00:00+00:00  133.56  133.6116  126.382  132.05  610813941      4738826  129.930251
2021-01-11 05:00:00+00:00  129.00  131.4500  126.860  127.14  485275646      3428760  129.217308
2021-01-18 05:00:00+00:00  127.72  139.8500  126.938  139.07  430076389      2847428  133.602730
2021-01-25 05:00:00+00:00  143.13  145.0900  130.210  131.96  719191985      6060399  139.474356
2021-02-01 05:00:00+00:00  133.65  137.4200  130.930  136.76  440177972      3587095  135.181482

> api.get_bars('AAPL', '1Month', start='2021-01-01', limit=5).df
                             open     high      low   close      volume  trade_count        vwap
timestamp                                                                                       
2021-01-01 05:00:00+00:00  133.56  145.090  126.382  131.96  2245357961     17075413  133.536588
2021-02-01 05:00:00+00:00  133.65  137.877  118.390  121.26  1835475446     15767259  130.118366
2021-03-01 05:00:00+00:00  123.78  128.720  116.210  122.15  2651884780     20877330  121.751073
2021-04-01 04:00:00+00:00  123.65  136.980  122.490  131.46  1829969140     13137533  131.886826
2021-05-01 04:00:00+00:00  132.01  134.070  122.250  124.61  1677551325     12415537  126.791493

> api.get_bars('AAPL', '3Month', start='2021-01-01', limit=5).df
                             open    high     low   close      volume  trade_count        vwap
timestamp                                                                                     
2021-01-01 05:00:00+00:00  133.56  145.09  116.21  122.15  6732718187     53720002  127.962630
2021-04-01 04:00:00+00:00  123.65  137.41  122.25  136.96  5112118746     36132507  129.575096
2021-07-01 04:00:00+00:00  136.51  157.26  135.76  141.50  5176549968     36663413  147.114577
2021-10-01 04:00:00+00:00  141.80  182.13  138.27  177.57  5704299815     41417607  160.096044
2022-01-01 05:00:00+00:00  177.81  182.94  152.00  166.23  3930398401     34027628  168.967150

> api.get_bars('AAPL', '6Month', start='2021-01-01', limit=5).df
                             open    high     low   close       volume  trade_count        vwap
timestamp                                                                                      
2021-01-01 05:00:00+00:00  133.56  145.09  116.21  136.96  11844836933     89852509  128.658555
2021-07-01 04:00:00+00:00  136.51  182.13  135.76  177.57  10880849783     78081020  153.920128
2022-01-01 05:00:00+00:00  177.81  182.94  152.00  166.23   3930398401     34027628  168.967150

> api.get_bars('AAPL', '12Month', start='2021-01-01', limit=5).df
                             open    high     low   close       volume  trade_count        vwap
timestamp                                                                                      
2021-01-01 05:00:00+00:00  133.56  182.13  116.21  177.57  22725686716    167933529  140.753564
2022-01-01 05:00:00+00:00  177.81  182.94  152.00  166.23   3930398401     34027628  168.967150
```

**Comment by akarun2405** [comment]
I can also confirm that the API is returning 1M 1W candles etc.. Thank you so much

**Comment by akarun2405** [comment]
@gnvk When I tried it right now, I'm getting an exception thrown for time intervals like 1Month or 1Week. I get this following error:
```
>>> api.get_bars('AAPL', '1Month', start='2021-01-01', limit=5).df

Traceback (most recent call last):
  File "/Users/arun/opt/miniconda3/envs/.venv/lib/python3.10/site-packages/alpaca_trade_api/rest.py", line 210, in _one_request
    resp.raise_for_status()
  File "/Users/arun/opt/miniconda3/envs/.venv/lib/python3.10/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://data.alpaca.markets/v2/stocks/AAPL/bars?timeframe=1Month&adjustment=raw&start=2021-01-01&limit=5


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/arun/opt/miniconda3/envs/.venv/lib/python3.10/site-packages/alpaca_trade_api/rest.py", line 714, in get_bars
    bars = list(self.get_bars_iter(symbol,
  File "/Users/arun/opt/miniconda3/envs/.venv/lib/python3.10/site-packages/alpaca_trade_api/rest.py", line 700, in get_bars_iter
    for bar in bars:
  File "/Users/arun/opt/miniconda3/envs/.venv/lib/python3.10/site-packages/alpaca_trade_api/rest.py", line 621, in _data_get
    resp = self.data_get(path, data=data, api_version=api_version)
  File "/Users/arun/opt/miniconda3/envs/.venv/lib/python3.10/site-packages/alpaca_trade_api/rest.py", line 242, in data_get
    return self._request(
  File "/Users/arun/opt/miniconda3/envs/.venv/lib/python3.10/site-packages/alpaca_trade_api/rest.py", line 189, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/arun/opt/miniconda3/envs/.venv/lib/python3.10/site-packages/alpaca_trade_api/rest.py", line 218, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: invalid timeframe: invalid timeframe format
```

**Comment by gnvk** [comment]
@akarun2405  Sorry for the inconvenience. We had a [maintenance](https://status.alpaca.markets/incidents/0khrr5y5764y) during the weekend and accidentally the previous version was restored. The new version (that has weekly and monthly bars) are out again.

**Comment by gnvk** [comment]
> Thank you for confirmation. Any idea when the service will be restored.

I restored it before commenting.

> Also is there a way to specify IEX vs SIP while fetching the historical data? I think by default I get IEX prices.

On the REST API you can use the `feed` query parameter. However, if I see correctly, it's not available in the Python SDK.

If you don't explicitly specify the feed, the default feed logic is the following:
- if you have unlimited subscription, it's SIP
- if you're on the free plan and the `end` timestamp is before the last 15 minutes, it's SIP
- otherwise (free plan & last 15 minutes) it's IEX
