### ISSUE TITLE
[Bug]: lots of errors on long-short example

### ISSUE THREAD

**Issue by sellingmoney** [alpacahq/alpaca-trade-api-python#570]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I run, nothing happens and I get the following errors:

*lots of errors*

**Comment by Dylan-86** [comment]
I see the same.

Here the output:

```
Exception in thread Thread-51:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-4-95a4b1e77432>", line 313, in getPercentChanges
TypeError: list indices must be integers or slices, not str
Exception in thread Thread-52:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-4-95a4b1e77432>", line 270, in getTotalPrice
TypeError: list indices must be integers or slices, not str
Exception in thread Thread-53:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-4-95a4b1e77432>", line 270, in getTotalPrice
TypeError: list indices must be integers or slices, not str
Exception in thread Thread-49:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-4-95a4b1e77432>", line 258, in rerank
IndexError: list index out of range
Exception in thread Thread-55:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-4-95a4b1e77432>", line 293, in submitOrder
TypeError: '>' not supported between instances of 'NoneType' and 'int'
Exception in thread Thread-54:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-4-95a4b1e77432>", line 283, in sendBatchOrder
IndexError: list index out of range
Exception in thread Thread-48:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-4-95a4b1e77432>", line 175, in rebalance
IndexError: list index out of range

```

**Comment by sellingmoney** [comment]
same here

**Comment by haxdds** [comment]
Hi @sellingmoney and @Dylan-86

What version of the SDK are you using? 
We've fixed some bugs in the long short example but they haven't been published yet to PyPi.

The fixes will be available in the next release of the SDK.

Also keep in mind that you will need a  [premium data subscription](https://www.alpaca.markets/data) to properly run the example since it depends on recent historical data.

**Comment by Dylan-86** [comment]
Hi,
- SDK: Latest
- Yes I have a premium data subscription

I will try to clone the repo later today and let you know.
