### ISSUE TITLE
[Bug]: calling get_barse that call the method _data_get_v2 throw error TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by ObaidaAlhaasan** [alpacahq/alpaca-trade-api-python#594]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi all,

I'm trying to load data using the method get_barse and I'm getting an error **TypeError: 'NoneType' object is not iterable** that thrown in method _data_get_v2

```python
[/usr/local/lib/python3.7/dist-packages/alpaca_trade_api/rest.py](https://localhost:8080/#) in _data_get_v2(self, endpoint, symbol, **kwargs)
    562                                  data=data, api_version='v2')
    563             items = resp.get(endpoint, [])
--> 564             for item in items:
    565                 yield item
    566             total_items += len(items)

TypeError: 'NoneType' object is not iterable
```

### Steps To Reproduce

```markdown
1. import alpaca-trade-api in google colab
2. Load the method download_data
3. Execute the method download_data



data = download_data(API_KEY, API_SECRET, start_date = '2021-02-01', end_date = '2021-10-05', 
                     ticker_list = ['AAPL', 'GOOG', 'AMZN'], 
                     time_interval= '1Min')
```

```python
def download_data(API_KEY, API_SECRET, ticker_list, start_date, end_date, time_interval
) -> pd.DataFrame:
    start = start_date
    end = end_date
    time_interval = time_interval
    API_DATA_URL = 'https://data.alpaca.markets/v2/stocks'
    api = REST(API_KEY, API_SECRET, API_DATA_URL)

    NY = "America/New_York"
    start_date = pd.Timestamp(start_date, tz=NY)
    end_date = pd.Timestamp(end_date, tz=NY) + pd.Timedelta(days=1)
    date = start_date
    data_df = pd.DataFrame()
    while date != end_date:
        start_time = (date + pd.Timedelta("09:30:00")).isoformat()
        end_time = (date + pd.Timedelta("15:59:00")).isoformat()
        for tic in ticker_list:
            barset = api.get_bars(tic, TimeFrame.Minute, start=start_time, end=end_time, limit=500, adjustment='raw').df

            barset['tic'] = tic
            barset = barset.reset_index()
            data_df = data_df.append(barset)

        print(("Data before ") + end_time + " is successfully fetched")

        date = date + pd.Timedelta(days=1)
        
        if date.isoformat()[-14:-6] == "01:00:00":
            date = date - pd.Timedelta("01:00:00")
        elif date.isoformat()[-14:-6] == "23:00:00":
            date = date + pd.Timedelta("01:00:00")
        if date.isoformat()[-14:-6] != "00:00:00":
            raise ValueError("Timezone Error")
    """times = data_df['time'].values
    for i in range(len(times)):
        times[i] = str(times[i])
    data_df['time'] = times"""

    return data_df

```
```


### Anything else?

_No response_

**Comment by ObaidaAlhaasan** [comment]
Sure

**Comment by jabowery** [comment]
Using the code in historic_async.py I'm still getting this error and I'm using version 2.2.0 of "the SDK" if, by "the SDK" you mean `alpaca-trade-api-python`:

```
  dummy_thread = threading.currentThread()
Connected to pydev debugger (build 211.7142.13)
Getting Bars data for 1 symbols, timeframe: 1Day between dates: start=2013-05-01, end=2022-05-17
timestamp
2015-12-01 05:00:00+00:00    122.83
2015-12-02 05:00:00+00:00    122.87
2015-12-03 05:00:00+00:00    119.54
2015-12-04 05:00:00+00:00    120.58
2015-12-07 05:00:00+00:00    121.75
                              ...  
2022-05-11 04:00:00+00:00    117.94
2022-05-12 04:00:00+00:00    117.72
2022-05-13 04:00:00+00:00    115.98
2022-05-16 04:00:00+00:00    115.86
2022-05-17 04:00:00+00:00    114.46
Name: close, Length: 1627, dtype: float64
Total of 1 Bars, and 0 empty responses.
python-BaseException
Traceback (most recent call last):
  File "/home/jabowery/anaconda3/envs/alpacangrn/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/jabowery/anaconda3/envs/alpacangrn/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/jabowery/dev/alex/alpacangrn/historic_async.py", line 91, in main
    results.extend(
TypeError: 'NoneType' object is not iterable
tradeapi.__version__
Python 3.10.4 | packaged by conda-forge | (main, Mar 24 2022, 17:38:57) [GCC 10.3.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.4.0 -- An enhanced Interactive Python. Type '?' for help.
PyDev console: using IPython 8.4.0
Out[1]: '2.2.0'

```
