### ISSUE TITLE
Websocket exception

### ISSUE THREAD

**Issue by carles-estevadeordal** [alpacahq/alpaca-trade-api-python#64]
The websocket sometimes gives an exception but it is not clear if it reconnects...

Task exception was never retrieved
future: <Task finished coro=<StreamConn._consume_msg() done, defined at /opt/conda/lib/python3.6/site-packages/alpaca_trade_api/stream2.py:46> exception=ConnectionClosed('WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason',)>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/websockets/protocol.py", line 674, in transfer_data
    message = yield from self.read_message()
  File "/opt/conda/lib/python3.6/site-packages/websockets/protocol.py", line 742, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "/opt/conda/lib/python3.6/site-packages/websockets/protocol.py", line 815, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "/opt/conda/lib/python3.6/site-packages/websockets/protocol.py", line 884, in read_frame
    extensions=self.extensions,
  File "/opt/conda/lib/python3.6/site-packages/websockets/framing.py", line 99, in read
    data = yield from reader(2)
  File "/opt/conda/lib/python3.6/asyncio/streams.py", line 674, in readexactly
    yield from self._wait_for_data('readexactly')
  File "/opt/conda/lib/python3.6/asyncio/streams.py", line 464, in _wait_for_data
    yield from self._waiter
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/alpaca_trade_api/stream2.py", line 50, in _consume_msg
    r = await ws.recv()
  File "/opt/conda/lib/python3.6/site-packages/websockets/protocol.py", line 434, in recv
    yield from self.ensure_open()
  File "/opt/conda/lib/python3.6/site-packages/websockets/protocol.py", line 658, in ensure_open
    ) from self.transfer_data_exc
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason

**Comment by aprsa** [comment]
Same issue here; it does not reconnect as no new messages come through the stream. Alpaca never passes the exception. Could it be that the websocket doesn't raise an exception so that alpaca api cannot catch it?

**Comment by rvishal11** [comment]
Its an open bug: https://github.com/aaugustin/websockets/labels/bug

Its added as a milestone for the 8.0(https://github.com/aaugustin/websockets/milestone/4) release

**Comment by alexonab** [comment]
Could the reconnect handling that was added to polygon streamconn also be added to the default streamconn?

**Comment by umitanuki** [comment]
I believe the websocket connection handling has changed over time. Please open a new issue if you encounter new one.
